### ISSUE TITLE
arm64e?

### ISSUE THREAD

**Issue by genevera** [SimulPiscator/vpcm#1]
Not that I have any earthly idea how to do this but it would be pretty cool to get this compiled for arm... I tried changing the architectures and got a codeless kext :(

**Comment by SimulPiscator** [comment]
Thanks for the heads up. I've modified project and source so it results in a universal binary kext. Let me know if it works for you.

**Comment by genevera** [comment]
Oh that 👍 was just to ack the commit.  This does in fact compile to a universal binary but the code signing req's for kexts in big sur are such that I can't install the release build no matter how i try and sign.

I think I probably need to compile for debug and install that way.  Or it may be time to re-factor this as an audio driver?

**Comment by SimulPiscator** [comment]
I don't think there is a lot of performance penalty involved in the debug version. The "hard" work is memcpy and/or multiplication, which is unlikely to profit from compiler optimization.
