### ISSUE TITLE
vpcm kext does not seem to install in MacOS Monterey

### ISSUE THREAD

**Issue by mcquiggi** [SimulPiscator/vpcm#3]
The build process works, but moving the vpcm.kext file to the specified location and rebooting the machine does not install it.  There is no /dev/vpcmctl device created. kextstat does not show anything related to vpcm and I cannot find any errors in regard to the attempted loading either.

I have Monterey 12.5.1.

Any further info or suggestions would be appreciated!

K. McQuiggin

**Comment by SimulPiscator** [comment]
For me, it works with Monterey 12.5.1. Maybe you moved the kext into `/System/Library/Extensions` rather than `/Library/Extensions`?

**Comment by mcquiggi** [comment]
Hi:

Thanks for the reply.  Nope, I moved it to /Library/Extensions.  I will try it again, and I will also try a kextload to see what it says.

I’ll let you know what happens!!

Kevin

**Comment by mcquiggi** [comment]
Looks like a permissions issue:

***@***.*** Extensions % sudo kextload vpcm.kext
Password:
Executing: /usr/bin/kmutil load -p /Library/Extensions/vpcm.kext
Error Domain=KMErrorDomain Code=30 "Validating extension failed: Kext org.vpcm.driver.vpcm v0.0.1 in executable kext bundle org.vpcm.driver.vpcm at /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext:

Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/_CodeSignature
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/_CodeSignature/CodeResources
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/MacOS
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/MacOS/vpcm
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/Info.plist
Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Validating extension failed: Kext org.vpcm.driver.vpcm v0.0.1 in executable kext bundle org.vpcm.driver.vpcm at /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext:

Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/_CodeSignature
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/_CodeSignature/CodeResources
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/MacOS
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/MacOS/vpcm
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/org.vpcm.driver.vpcm.pI0C4B/vpcm.kext/Contents/Info.plist
Authenticating extension failed: Bad code signature}
***@***.*** Extensions %

Any suggestions?

Kevin

**Comment by SimulPiscator** [comment]
There might be a problem with architectures. What is the output of 
`file vpcm.kext/Contents/MacOS/vpcm`
?

**Comment by SimulPiscator** [comment]
Another possibility is that you moved the kext to a different machine. Code signing is set to "execute locally", so it would not allow execution on a different machine.

**Comment by mcquiggi** [comment]
No, I am on the same machine that I built the project on.

I will re-build and look more closely for compiler warnings etc.

**Comment by mcquiggi** [comment]
I note from the buildtime issues window that Xcode is warning that the target MacOS deployment target of 10.6 is not in Xcode’s supported range.



I will update deployment target to 12.3 (top end of the stated supported versions) and build again, then see whether that helps.

Kevin

**Comment by mcquiggi** [comment]
Perhaps relevant too is that this machine is a 2022 MacBook Pro with the M2 CPU.

**Comment by SimulPiscator** [comment]
Sorry, I forgot that you need to disable SIP in order to use kexts that are not signed: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

**Comment by SimulPiscator** [comment]
I've added a note about disabling kext signing to the README.md file.

**Comment by mcquiggi** [comment]
Thanks!!

**Comment by mcquiggi** [comment]
Thanks for the help.  Here’s the output of vpcm:

***@***.*** MacOS % pwd
/Library/Extensions/vpcm.kext/Contents/MacOS
***@***.*** MacOS % ls -al
total 664
drwxr-xr-x  3 mcquiggi  staff      96  4 Sep 10:40 .
drwxr-xr-x  5 mcquiggi  staff     160  4 Sep 10:40 ..
-rwxr-xr-x  1 mcquiggi  staff  338704  4 Sep 10:40 vpcm
***@***.*** MacOS % ./vpcm
zsh: exec format error: ./vpcm
***@***.*** MacOS % sudo ./vpcm
./vpcm: ./vpcm: cannot execute binary file
***@***.*** MacOS %

**Comment by SimulPiscator** [comment]
Hi, sorry for being unclear: I was asking for the output of the "file" command when applied to the vpcm executable. It will tell which architectures are present in the file.
